name: test
on: push

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go:
          # - "1.20"
          - "1.21.0-rc.3"
        os: # https://github.com/actions/virtual-environments
          - "macos-13"
          - "macos-12"
          - "macos-11"
          - "ubuntu-22.04"
          - "ubuntu-20.04"
          - "windows-latest"
    runs-on: ${{ matrix.os }} 
    name: ${{ matrix.os }} / Go ${{ matrix.go }} test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache: false
      - run: go test -v
